In [1]:
# Create a function to check whether numpy array has Zero values or not.

# numpy.all() function returns false if it founds 0 in array.
import numpy as np
x=np.array([4,7,84,1,22])
y=np.array([44,55,77,88,0])
print(x)
print(y)
print('For array x',np.all(x))
print('For array y',np.all(y))

[ 4  7 84  1 22]
[44 55 77 88  0]
For array x True
For array y False


In [2]:
# Consider an array contains marks of students. Find the median and mean of students who got passing marks.
import numpy as np
x=np.array([75,87,78,69,77,81]) # marks of 6 subjects
print('Mean is ',x.mean())
print('Median is ',np.median(x))

Mean is  77.83333333333333
Median is  77.5


In [3]:
# Consider an array containing date of birth of students (Use np.datetime64('2018-02-01'))
# . Find the age of all students.
# If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth

import numpy as np
from datetime import datetime
dates_of_birth = np.array(['2009-04-07','2002-02-07','2000-07-07'],dtype='datetime64')
labels=[]

today=datetime.now().date()
today=np.datetime64(today)

print(np.timedelta64(365,'D'))
for date in dates_of_birth:
    days_diff = today - date
    years_diff = days_diff/np.timedelta64(365,'D')
    if int(years_diff) ==18:
        labels.append("First")
    elif int(years_diff) ==19:
        labels.append("Second")
    elif int(years_diff) ==20:
        labels.append("Third")
    elif int(years_diff) ==21:
        labels.append("Fourth")
    else:
        labels.append("Undefined")

print("Labels: ",labels)

365 days
Labels:  ['Undefined', 'Second', 'Third']


In [4]:
# Create a function to sort 2d Array by a column
import numpy as np
x=np.array([[49,144,175],[44,58,200]])
np.sort(x,axis=0)

array([[ 44,  58, 175],
       [ 49, 144, 200]])