In [1]:
print('Start')
import numpy as np
import pandas as pd
print('done')
print(np.__version__)

Start
done
1.21.0


In [2]:
# Create one hot encoding of an array.
x=int(input("Enter the number of elements"))
print("Enter the elements")
arr=np.array(list(map(int,input().split())))
shape=(x,arr.max())
encoding=np.zeros(shape)

for i in range(x):
    encoding[i,arr[i]-1]=1
    
encoding

Enter the number of elements6
Enter the elements
2 3 2 2 2 1


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [3]:
# Drop all missing values from an array Input
a=np.array([1,2,3,np.nan,5,6,7,np.nan])
print('Original',np.isnan(a))
a=a[~np.isnan(a)]
print(a)
# Missing values are reffered as True
print('After',np.isnan(a))

Original [False False False  True False False False  True]
[1. 2. 3. 5. 6. 7.]
After [False False False False False False]


In [4]:
# Find Local maxima from an array
from scipy.signal import argrelextrema
print("Enter the element of array:")
a2=np.array(list(map(int,input().split())))

loc_max=np.array(argrelextrema(a2, np.greater))
loc_min=np.array(argrelextrema(a2, np.less))

print("local maxmima:",loc_max)
print("local minima:",loc_min)

Enter the element of array:
1 3 7 1 2 6 0 1
local maxmima: [[2 5]]
local minima: [[3 6]]


In [5]:
# From the given 1d array arr, generate a 2d matrix using strides,
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
w=int(input("Enter the window size(w):"))
s=int(input("Enter the stride value(s):"))
res=sliding_window_view(arr, window_shape = w)[::s]
res

Enter the window size(w):4
Enter the stride value(s):2


array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [ ]:
pip install numpy